### ISSUE TITLE
Monitoring with piscope not working

### ISSUE THREAD

**Issue by wkoffel** [sarfata/pi-blaster#56]
pi-blaster is working nicely for me at first blush (in fact, it's simplicity was a huge relief after battling with things like WiringPi and *still* not being able to massage my signal the way I needed it for servo control).

I have been monitoring GPIO pins with [piscope](http://abyz.co.uk/rpi/pigpio/piscope.html), which works fine in all my test cases (a number of different libraries, `gpio` command line tool, and input signals).  **However**, I don't see any signals on the pins I control with pi-blaster.

Is anyone using these two together?  I haven't found any mention of incompatibility, but I also don't know much about the internals of pigpiod or pi-blaster.

**Comment by sarfata** [comment]
I did not know about [piscope](https://github.com/joan2937/pigpio/blob/master/pigpio.c). Looks like a cool project.

I do not see why it would not work because we should all be pointing to the same areas in memory. Both projects are using DMA though so they might be some conflicts there.

Can you see other pins (non pi-blaster controlled) change values (via piscope) while controlling pins via pi-blaster?
